students/urls.py
from django.urls import path
from . import views

app_name = 'students'

urlpatterns = [
    path('', views.Index.as_view(), name='index'),

    path('profile/edit/', views.EditProfile.as_view(), name='edit_profile'),
    path('profile/reminder/confirm/', views.confirm_profile_reminder, name='confirm_profile_reminder'),
    path('profile/information/ta/update/', views.update_profile_ta, name='update_profile_ta'),
    path('profile/information/', views.ShowProfile.as_view(), name='show_profile'),
    path('profile/resume/upload/', views.upload_resume, name='upload_resume'),
    path('profile/resume/delete/', views.delete_resume, name='delete_resume'),

    path('confidential_information/check/', views.check_confidentiality, name='check_confidentiality'),
    path('confidential_information/submit/', views.submit_confidentiality, name='submit_confidentiality'),
    path('confidential_information/edit/', views.EditConfidentiality.as_view(), name='edit_confidentiality'),
    path('confidential_information/delete/', views.delete_confidential_information, name='delete_confidential_information'),
    path('confidential_information/', views.show_confidentiality, name='show_confidentiality'),

    path('jobs/explore/', views.ExploreJobs.as_view(), name='explore_jobs'),
    path('jobs/history/', views.history_jobs, name='history_jobs'),
    path('jobs/favourite/', views.favourite_jobs, name='favourite_jobs'),
    path('sessions/<str:session_slug>/jobs/<str:job_slug>/apply/', views.ApplyJob.as_view(), name='apply_job'),
    path('sessions/<str:session_slug>/jobs/<str:job_slug>/select-favourite-job/', views.select_favourite_job, name='select_favourite_job'),
    path('sessions/<str:session_slug>/jobs/<str:job_slug>/offered/', views.accept_decline_job, name='accept_decline_job'),
    path('sessions/<str:session_slug>/jobs/<str:job_slug>/make_decision/', views.make_decision, name='make_decision'),
    path('sessions/<str:session_slug>/jobs/<str:job_slug>/contract-termination/', views.terminate_job, name='terminate_job'),
    path('sessions/<str:session_slug>/jobs/available/', views.AvailableJobs.as_view(), name='available_jobs'),
    path('sessions/<str:session_slug>/jobs/<str:job_slug>/details/', views.show_job, name='show_job'),

    path('applications/<str:app_slug>/re-accept/', views.reaccept_application, name='reaccept_application'),
    path('applications/<str:app_slug>/', views.show_application, name='show_application'),

    path('download/users/<str:username>/i/<str:item>/files/<str:filename>/', views.download_file, name='download_file')
]

ta_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import handler400, handler403, handler404, handler500
from ta_app import views

urlpatterns = [
    path('app/users/', include('users.urls')),
    path('app/administrators/', include('administrators.urls')),
    path('app/instructors/', include('instructors.urls')),
    path('app/students/', include('students.urls')),
    path('app/observers/', include('observers.urls')),
    path('app/summernote/', include('django_summernote.urls')),
    path('app/impersonate/', include('impersonate.urls')),

    path('app/', views.app_home, name='app_home'),
    path('logout/', views.site_logout, name='logout'),
    path('', views.landing_page, name='landing_page')
]

if settings.DEBUG:
    urlpatterns += [
        path('admin/', admin.site.urls)
    ]

if settings.LOCAL_LOGIN:
    urlpatterns += [
        path('accounts/', include('accounts.urls'))
    ]

handler400 = views.bad_request
handler403 = views.permission_denied
handler404 = views.page_not_found
handler500 = views.internal_server_error

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('profile/photo/upload/', views.upload_avatar, name='upload_avatar'),
    path('profile/photo/delete/', views.delete_avatar, name='delete_avatar'),
    path('profile/<str:username>/details/', views.show_user, name='show_user'),
]

administrators/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify
from django.core.validators import MaxValueValidator, MinValueValidator
from django.utils.translation import gettext_lazy as _

import datetime as dt

from ta_app import utils


class Term(models.Model):
    """ Create a Term model """
    code = models.CharField(max_length=20, unique=True)
    name = models.CharField(max_length=256)
    by_month = models.IntegerField(
        default=4,
        validators=[MinValueValidator(1), MaxValueValidator(12)]
    )
    max_hours = models.IntegerField(
        default=192,
        validators=[MinValueValidator(0), MaxValueValidator(4000)]
    )
    class Meta:
        ordering = ['pk']

    def __str__(self):
        return self.code


class CourseCode(models.Model):
    """ Create a CourseCode model """
    name = models.CharField(max_length=5, unique=True)
    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name

class CourseNumber(models.Model):
    """ Create a CourseNumber model """
    name = models.CharField(max_length=5, unique=True)
    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name

class CourseSection(models.Model):
    """ Create a CourseSection model """
    name = models.CharField(max_length=12, unique=True)
    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name

class Course(models.Model):
    ''' Create a Course model '''
    code = models.ForeignKey(CourseCode, on_delete=models.DO_NOTHING)
    number = models.ForeignKey(CourseNumber, on_delete=models.DO_NOTHING)
    section = models.ForeignKey(CourseSection, on_delete=models.DO_NOTHING)
    term = models.ForeignKey(Term, on_delete=models.DO_NOTHING)
    name = models.CharField(max_length=256, null=True)
    overview = models.TextField(null=True, blank=True)
    job_description = models.TextField(null=True, blank=True)
    job_note = models.TextField(null=True, blank=True)
    is_active = models.BooleanField(default=True)
    slug = models.SlugField(max_length=256, unique=True)

    class Meta:
        unique_together = ['code', 'number', 'section', 'term']
        ordering = ['code', 'number', 'term', 'section']

    def __str__(self):
        return '{0} {1} {2}'.format(self.code, self.number, self.section)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.code.name  + ' ' + self.number.name + ' ' + self.section.name + ' ' + self.name + ' ' + self.term.code)
        super(Course, self).save(*args, **kwargs)


class Session(models.Model):
    """ Create a Session model """

    year = models.CharField(max_length=4)
    term = models.ForeignKey(Term, on_delete=models.DO_NOTHING)
    title = models.CharField(max_length=256)
    description = models.TextField(null=True, blank=True)
    note = models.TextField(null=True, blank=True)
    is_visible = models.BooleanField(default=False)
    is_archived = models.BooleanField(default=False)

    created_at = models.DateField(default=dt.date.today)
    updated_at = models.DateField(default=dt.date.today)
    slug = models.SlugField(max_length=256, unique=True)

    class Meta:
        unique_together = ['year', 'term']
        ordering = ['-year', 'term']

    def __str__(self):
        return '{0} {1} {2}'.format(self.year, self.term.code, self.title)

    def save(self, *args, **kwargs):
        """ Make a slug """
        self.slug = slugify(self.year + ' ' + self.term.code)
        super(Session, self).save(*args, **kwargs)


class Job(models.Model):
    course_overview = models.TextField(null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    note = models.TextField(null=True, blank=True)
    session = models.ForeignKey(Session, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    instructors = models.ManyToManyField(User)

    # Admins can assign TA hours
    assigned_ta_hours = models.FloatField(
        default=0.0,
        validators=[MinValueValidator(0), MaxValueValidator(4000)]
    )

    # Add up all student's TA hours
    accumulated_ta_hours = models.FloatField(
        default=0.0,
        validators=[MinValueValidator(0), MaxValueValidator(4000)]
    )

    is_active = models.BooleanField(default=True)
    created_at = models.DateField(default=dt.date.today)
    updated_at = models.DateField(default=dt.date.today)

    def __str__(self):
        return '{0} {1} {2} {3} {4}'.format(self.session.year, self.session.term.code, self.course.code.name, self.course.number.name, self.course.section.name)
    class Meta:
        ordering = ['session', 'course']


class Classification(models.Model):
    year = models.CharField(max_length=10)
    name = models.CharField(max_length=10)
    wage = models.FloatField()
    is_active = models.BooleanField(default=True)
    slug = models.SlugField(max_length=256, unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.year + ' ' + self.name)
        super(Classification, self).save(*args, **kwargs)

    class Meta:
        unique_together = ['year', 'name']
        ordering = ['-year', '-wage']


class Application(models.Model):
    """ This is a model for applications of students """

    PREFERENCE_CHOICES = [
        ('0', 'Select'),
        ('1', 'Not at all'),
        ('2', 'Marginally'),
        ('3', 'Somewhat'),
        ('4', 'Very'),
        ('5', 'Most')
    ]

    # instructor_preference removed
    NONE = '0'
    NO_PREFERENCE = '1'
    ACCEPTABLE = '2'
    REQUESTED = '3'
    CRITICAL_REQUESTED = '4'

    INSTRUCTOR_PREFERENCE_CHOICES = [
        (NONE, 'None'),
        (NO_PREFERENCE, 'No Preference'),
        (ACCEPTABLE, 'Acceptable'),
        (REQUESTED, 'Requested'),
        (CRITICAL_REQUESTED, 'Critical Requested')
    ]

    applicant = models.ForeignKey(User, on_delete=models.CASCADE)
    job = models.ForeignKey(Job, on_delete=models.CASCADE)

    supervisor_approval = models.BooleanField()
    how_qualified = models.CharField(max_length=1, choices=PREFERENCE_CHOICES)
    how_interested = models.CharField(max_length=1, choices=PREFERENCE_CHOICES)
    availability = models.BooleanField()
    availability_note = models.TextField(null=True, blank=True)

    classification = models.ForeignKey(Classification, on_delete=models.DO_NOTHING, null=True, blank=True)
    note = models.TextField(null=True, blank=True)

    instructor_preference = models.CharField(max_length=1, choices=INSTRUCTOR_PREFERENCE_CHOICES, default=NONE)
    sta_confirmation = models.BooleanField(default=False)

    is_declined_reassigned = models.BooleanField(default=False)
    is_terminated = models.BooleanField(default=False)

    created_at = models.DateField(default=dt.date.today)
    updated_at = models.DateField(default=dt.date.today)
    slug = models.SlugField(max_length=256, unique=True)

    class Meta:
        ordering = ['job', 'applicant']

    def save(self, *args, **kwargs):
        self.slug = slugify(self.job.session.slug + ' ' + self.job.course.slug + ' application by ' + self.applicant.username)
        super(Application, self).save(*args, **kwargs)


class ApplicationReset(models.Model):
    ''' Application Reset'''

    user = models.CharField(max_length=256)
    application = models.ForeignKey(Application, on_delete=models.CASCADE)
    created_at = models.DateField(default=dt.date.today)


class ApplicationStatus(models.Model):
    '''
    Application Status

    # Updates
    Cancelled = Terminated
    '''
    
    ASSSIGNED_CHOICES = [(utils.NONE, 'None'), (utils.SELECTED, 'Selected'), (utils.OFFERED, 'Offered'), (utils.ACCEPTED, 'Accepted'), (utils.DECLINED, 'Declined'), (utils.CANCELLED, 'Cancelled')]

    application = models.ForeignKey(Application, on_delete=models.CASCADE)
    assigned = models.CharField(max_length=1, choices=ASSSIGNED_CHOICES, default=utils.NONE)
    assigned_hours = models.FloatField(
        default=0.0,
        validators=[MaxValueValidator(4000)]
    )
    parent_id = models.CharField(max_length=256, null=True, blank=True)
    has_contract_read = models.BooleanField(default=False)

    created_at = models.DateField(default=dt.date.today)

    class Meta:
        ordering = ['pk']


class WorktagSetting(models.Model):
    ''' Set up worktag hours for admin documents '''

    application = models.OneToOneField(Application, on_delete=models.CASCADE, primary_key=True)
    job_id = models.BigIntegerField()
    program_info = models.JSONField()
    worktag = models.CharField(max_length=100)
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)

    class Meta:
        ordering = ['-pk']


class AdminDocuments(models.Model):
    '''
    Admin Documents

    # Updates: made field changes
    efrom -> no longer available
    speed_chart -> worktag
    processed -> new
    position_number -> new
    '''
    application = models.OneToOneField(Application, on_delete=models.CASCADE, primary_key=True)
    
    position_number = models.CharField(max_length=10, null=True, blank=True)
    pin = models.CharField(max_length=4, null=True, blank=True)
    tasm = models.BooleanField(default=False)
    eform = models.CharField(max_length=6, unique=True, null=True, blank=True)
    speed_chart = models.CharField(max_length=4, null=True, blank=True)
    processing_note = models.TextField(null=True, blank=True)
    worktag = models.CharField(max_length=100, null=True, blank=True)
    processed = models.CharField(max_length=4, null=True, blank=True)


class AdminDocumentsUser(models.Model):
    ''' Admin Docs by Users '''
    user = models.CharField(max_length=256)
    document = models.ForeignKey(AdminDocuments, on_delete=models.CASCADE)
    created_at = models.DateField(default=dt.date.today)

    class Meta:
        ordering = ['-pk']


class Favourite(models.Model):
    ''' Favourite Job '''

students/templates/students/jobs/cancel_job.html
{% extends 'ta_app/base.html' %}
{% block content %}

{% include 'students/_menu.html' %}
<div class="row">
  <div class="col-md-4">
    {% include 'ta_app/pages/_left_aside.html' with view_name='job_applications' title='Contract Termination' data=app.job %}

    <div class="col-10 mx-auto text-center mt-4">
      <table class="table">
        <tr class="text-dark-gray">
          <td>Job Details</td>
        </tr>
        <tr>
          <td>{% include 'ta_app/jobs/_modal_job_details.html' with data=app.job %}</td>
        </tr>
      </table>
    </div>

    <div class="left-aside-btn-groups">
      <a class="btn btn-outline-primary" href="{{ request.GET.next }}">Back to History of Jobs</a>
    </div>
  </div>

  <div class="col-md-8">
    <div class="board col-11 mx-auto">

      <h3>Confirmation</h3>
      {% include 'ta_app/pages/_submit_note.html' %}

      <div class="card border-secondary bg-white mt-4 p-4">
        <p>I have been in contact with the TA administrator regarding the termination of this contract.</p>
        <p>Please click on the "Confirm" button to terminate this contract.</p>

        <form action="" method="post">
          {% csrf_token %}

          <input type="hidden" name="assigned_hours" value="{{ app.accepted.assigned_hours }}" />
          <input type="hidden" name="application" value="{{ app.id }}" />
          <input type="hidden" name="next" value="{{ request.GET.next }}" />

          <a class="btn btn-outline-secondary" href="{{ request.GET.next }}">Cancel</a>
          <input class="btn btn-danger" type="submit" value="Confirm" />
        </form>
      </div>

    </div>
  </div>
</div>

{% endblock %}

students/templates/students/jobs/explore_jobs.html
{% extends 'ta_app/base.html' %}
{% block content %}
{% load static %}

{% include 'students/_menu.html' %}
<div class="row">
	<div class="col-md-4">
		{% include 'ta_app/pages/_left_aside.html' with view_name='users' title='Explore Jobs' data=loggedin_user  %}

		<div class="left-aside-btn-groups">
			<a class="btn btn-warning" href="{% url 'students:favourite_jobs' %}">
				<i class="fa fa-star" aria-hidden="true"></i> Favourite Jobs ({{ favourites|length }})
			</a>
		</div>
	</div>

	<div class="col-md-8">

		<div class="board col-11 mx-auto">
			<h3 class="text-info">Current Openings Available</h3>

			{% include 'ta_app/users/_confi_info_expiry_status.html' with items=expiry_status path='students' %}

      {% if not can_apply %}
        {% include 'ta_app/pages/_apply_important_message.html' %}
      {% endif %}

			{% for session in visible_current_sessions %}
				<div class="visible-current-sessions gray-box p-3 m-3">
					<div class="gray-box-header">
						<img src="{% static 'ta_app/images/ubc-logo.jpeg' %}" width="25" alt="logo" />
						<h6>{{ session.year }} {{ session.term.name }} ({{ session.term.code }})</h6>
					</div>

					<hr class="mt-3 mb-2" />

					<div>
						<h5>
							{% if can_apply %}
								{% if session.is_locked %}
									<i class="fa fa-lock" aria-hidden="true"></i>
									<span class="text-dark-gray">{{ session.title }} (Jobs: {{ session.job_set.count }})</span>
									<a class="font-size-1" href="{% url 'students:edit_profile' %}?t=summary&session={{ session.slug }}">Confirm to unlock</a>
								{% else %}
									<a href="{% url 'students:available_jobs' session.slug %}">{{ session.title }} (Jobs: {{ session.job_set.count }})</a>
								{% endif %}
							{% else %}
								<span class="text-dark-gray">
									<i class="fa fa-lock" aria-hidden="true"></i>
									{{ session.title }} (Jobs: {{ session.job_set.count }})
								</span>
							{% endif %}
						</h5>
						{% if session.description %}
							<div>{{ session.description|safe }}</div>
						{% endif %}

						{% if session.note %}
							<div class="text-dark-gray">Note: {{ session.note|safe }}</div>
						{% endif %}
					</div>
				</div>
			{% empty %}

				<div class="text-dark-gray">
					<i class="fa fa-exclamation-triangle" aria-hidden="true"></i>
					No current sessions found.
				</div>

			{% endfor %}
		</div>

	</div>
</div>

{% endblock %}

students/templates/students/jobs/history_jobs.html
{% extends 'ta_app/base.html' %}
{% block content %}

{% include 'students/_menu.html' %}
<div class="row">
  <div class="col-md-3">
    {% include 'ta_app/pages/_left_aside_compact.html' with view_name='history_jobs' title='History of Jobs' %}

    <div class="left-aside-btn-groups">
      <a class="btn btn-outline-primary" href="{% url 'students:explore_jobs' %}">Back to Explore Jobs</a>
    </div>

    {% include 'ta_app/sessions/_note_session_archived.html' %}
  </div>

  <div class="col-md-9">
    <h5 class="text-info mb-3">
      <i class="fa fa-info-circle" aria-hidden="true"></i>
      Number of Jobs: {{ apps|length }}
    </h5>

    {% include 'students/jobs/_search_fields.html' with data=apps total=total_apps path='history_jobs' %}
    <table
      class="table table-bordered table-hover table-striped table-responsive-md text-center font-size-sm"
      data-toggle="table"
      data-sortable="true"
      data-classes=""
    >
      <thead>
        <tr>
          <th class="p-0"></th>
          <th data-sortable="true">Year</th>
          <th data-sortable="true">Term</th>
          <th data-sortable="true">Course (Job)</th>
          <th>Instructors</th>
          <th>Application</th>
          <th data-sortable="true">Applied Date</th>
          <th data-sortable="true">Status</th>
        </tr>
      </thead>
      <tbody>
        {% for app in apps %}
          <tr>
            <td>
              {% if app.job.session.is_archived %}
                <i class="fa fa-lock fa-lg text-secondary" aria-hidden="true"></i>
              {% else %}
                {% if app.offered %}
                  <i class="fa fa-envelope fa-lg text-chocolate" aria-hidden="true"></i>
                {% elif app.accepted and app.is_terminated %}
                    <i class="fa fa-envelope fa-lg text-chocolate" aria-hidden="true"></i>
                {% elif app.declined and app.is_declined_reassigned and app.declined.parent_id %}
                  <i class="fa fa-envelope fa-lg text-chocolate" aria-hidden="true"></i>
                {% endif %}
              {% endif %}
            </td>
            <td>{{ app.job.session.year }}</td>
            <td>{{ app.job.session.term.code }}</td>
            <td>
              <a href="{% url 'students:show_job' session_slug=app.job.session.slug job_slug=app.job.course.slug %}?next={{ request.get_full_path }}&p=History of Jobs">
                {{ app.job.course.code.name }} {{ app.job.course.number.name }} {{ app.job.course.section.name }}
              </a>

              {% if not app.job.is_active %}
                <br />
                <span class="badge badge-light">No longer available</span>
              {% endif %}
            </td>
            <td class="text-left">
              {% if app.job.instructors.count %}
                <ul class="list-no-ml">
                  {% for ins in app.job.instructors.all %}
                    <li>{{ ins.get_full_name }}</li>
                  {% endfor %}
                </ul>
              {% else %}
                None
              {% endif %}
            </td>
            <td>
              <a href="{% url 'students:show_application' app_slug=app.slug %}?next={{ request.get_full_path }}">View</a>
            </td>
            <td>
              <span class="d-none">{{ app.applied.created_at|date:"Y m d z" }}</span>
              {{ app.applied.created_at }}
            </td>
            <td>
              {% if app.offered %}

                {% include 'ta_app/applications/_app_status.html' with data=app.offered.get_assigned_display %}<br />
                <small class="text-dark-gray">{{ app.offered.created_at }}</small>
                <div>
                  <span class="font-weight-bold">{{ app.offered.assigned_hours }}</span> hours
                </div>

                {% if not app.job.session.is_archived %}

                  <hr />
                  {% if app.is_terminated %}
                    <a href="{% url 'students:terminate_job' session_slug=app.job.session.slug job_slug=app.job.course.slug %}?next={{ request.get_full_path }}">
                      Contract<br /> Termination
                    </a>
                  {% else %}
                    <a href="{% url 'students:accept_decline_job' session_slug=app.job.session.slug job_slug=app.job.course.slug %}?next={{ request.get_full_path }}">
                      Accept / Decline
                    </a>
                  {% endif %}

                {% endif %}

              {% elif app.accepted %}

                {% if app.is_declined_reassigned %}
                  <span class="badge badge-success">RE</span>
                {% endif %}

                {% include 'ta_app/applications/_app_status.html' with data=app.accepted.get_assigned_display %}<br />
                <small class="text-dark-gray">{{ app.accepted.created_at }}</small>
                <div>
                  <span class="font-weight-bold">{{ app.accepted.assigned_hours }}</span> hours
                </div>

                {% if app.is_terminated %}
                  <hr />
                  <a href="{% url 'students:terminate_job' session_slug=app.job.session.slug job_slug=app.job.course.slug %}?next={{ request.get_full_path }}">
                    Contract<br /> Termination
                  </a>
                {% endif %}

              {% elif app.declined %}

                {% include 'ta_app/applications/_app_status.html' with data=app.declined.get_assigned_display %}<br />
                <div><small class="text-dark-gray">{{ app.declined.created_at }}</small></div>

                {% if not app.job.session.is_archived and app.is_declined_reassigned and app.declined.parent_id %}

                  <hr />
                  <a href="{% url 'students:reaccept_application' app_slug=app.slug %}?next={{ request.get_full_path }}">
                    Re accept/decline
                  </a>

                {% endif %}

              {% elif app.cancelled %}

                {% include 'ta_app/applications/_app_status.html' with data=app.cancelled.get_assigned_display %}<br />
                <small class="text-dark-gray">{{ app.cancelled.created_at }}</small>

              {% else %}

                {% include 'ta_app/applications/_app_status.html' with data='None' %}

              {% endif %}
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>

    {% include 'ta_app/pages/_table_paginator.html' with data=apps %}

    {% include 'ta_app/pages/_note_reassigned_offer.html' %}
  </div>
</div>

{% endblock %}

students/templates/students/jobs/status_jobs.html
{% extends 'ta_app/base.html' %}
{% block content %}

{% include 'students/_menu.html' %}
<div class="row">
  <div class="col-md-4">
    {% include 'ta_app/pages/_left_aside.html' with view_name='users' title='Status of Jobs' data=loggedin_user %}

    <div class="left-aside-btn-groups">
      <a class="btn btn-outline-primary" href="{% url 'students:explore_jobs' %}">Back to Explore Jobs</a>
    </div>
  </div>

  <div class="col-md-8">

    <div class="board col-11 mx-auto">
      <h3>Summary</h3>

      <div>
        <h5>
          Total Jobs:
          <span class="text-secondary">{{ apps|length }}</span>
        </h5>
      </div>

      <div class="text-center">
        <h5 class="text-info">Total Accepted Assigned Hours</h5>
        <table class="table font-size-1">
          <thead>
            <tr>
              <th>Year-Term</th>
              <th>Total Hours</th>
            </tr>
          </thead>
          <tbody>
            {% for year_term, assigned_hours in total_accepted_assigned_hours.items %}
              <tr>
                <td>{{ year_term }}</td>
                <td>{{ assigned_hours }}</td>
              </tr>
            {% empty %}
              <tr>
                <td colspan="2">No matching records found</td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>

    </div>

  </div>
</div>

<div>
  <table
    class="table table-bordered table-hover table-striped table-responsive-md text-center font-size-1"
    data-toggle="table"
    data-sortable="true"
    data-classes=""
    data-pagination="true"
    data-search="true"
    data-page-size="50"
    data-page-list="[50, 100, 200, all]"
  >
    <thead>
      <tr>
        <th data-sortable="true">Year</th>
        <th data-sortable="true">Term</th>
        <th data-sortable="true">Job</th>
        <th data-sortable="true">Application</th>
        <th data-sortable="true">Applied at</th>
        <th data-sortable="true">Status</th>
      </tr>
    </thead>
    <tbody>
      {% for app in apps %}
        <tr>
          <td>{{ app.job.session.year }}</td>
          <td>{{ app.job.session.term.code }}</td>
          <td>
            <a href="{% url 'students:show_job' session_slug=app.job.session.slug job_slug=app.job.course.slug %}">
              {{ app.job.course.code.name }} {{ app.job.course.number.name }} {{ app.job.course.section.name }}
            </a>
          </td>
          <td>
            <a href="{% url 'students:show_application' app_slug=app.slug %}">View</a>
          </td>
          <td>{{ app.applied.created_at }}</td>
          <td>
            {% if app.offered %}

              {% include 'ta_app/applications/_app_status.html' with data=app.offered.get_assigned_display %}<br />
              <small class="text-muted">{{ app.offered.created_at }}</small>
              <div>
                <span class="font-weight-bold">{{ app.offered.assigned_hours }}</span> hours
              </div>

              <a href="{% url 'students:accept_decline_job' session_slug=app.job.session.slug job_slug=app.job.course.slug %}">Accept / Decline</a>

            {% elif app.accepted %}

              {% include 'ta_app/applications/_app_status.html' with data=app.accepted.get_assigned_display %}<br />
              <small class="text-muted">{{ app.accepted.created_at }}</small>
              <div>
                <span class="font-weight-bold">{{ app.accepted.assigned_hours }}</span> hours
              </div>

              {% if app.is_terminated %}
                <a href="{% url 'students:cancel_job' session_slug=app.job.session.slug job_slug=app.job.course.slug %}">Cancel</a>
              {% endif %}

            {% elif app.declined %}

              {% include 'ta_app/applications/_app_status.html' with data=app.declined.get_assigned_display %}<br />
              <small class="text-muted">{{ app.declined.created_at }}</small>

            {% elif app.cancelled %}

              {% include 'ta_app/applications/_app_status.html' with data=app.cancelled.get_assigned_display %}<br />
              <small class="text-muted">{{ app.cancelled.created_at }}</small>

            {% else %}

              {% include 'ta_app/applications/_app_status.html' with data='None' %}

            {% endif %}
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
</div>


<div>


  <div>


  </div>

</div>

{% endblock %}