administrators/urls.py
from django.urls import path
from . import views
from . import session_views
from . import job_views
from . import app_views
from . import course_views
from . import hr_views
from . import prep_views

app_name = 'administrators'

urlpatterns = [
    path('', views.Index.as_view(), name='index')
]


# Session

urlpatterns += [
    path('sessions/create/confirmation/', session_views.CreateSessionConfirmation.as_view(), name='create_session_confirmation'),
    path('sessions/create/setup-courses/', session_views.CreateSessionSetupCourses.as_view(), name='create_session_setup_courses'),
    path('sessions/create/', session_views.CreateSession.as_view(), name='create_session'),
    path('sessions/<str:session_slug>/delete/confirmation/', session_views.delete_session_confirmation, name='delete_session_confirmation'),
    path('sessions/<str:session_slug>/edit/', session_views.EditSession.as_view(), name='edit_session'),
    path('sessions/<str:session_slug>/details/', session_views.ShowSession.as_view(), name='show_session'),
    path('sessions/<str:session_slug>/report/summary/', session_views.ShowReportSummary.as_view(), name='show_report_summary'),
    path('sessions/<str:session_slug>/report/applicants/', session_views.ShowReportApplicants.as_view(), name='show_report_applicants'),
    path('sessions/current/', session_views.CurrentSessions.as_view(), name='current_sessions'),
    path('sessions/archived/', session_views.ArchivedSessions.as_view(), name='archived_sessions'),
    path('sessions/extra-courses/add/', session_views.AddExtraCourses.as_view(), name='add_extra_courses'),
]


# Job

urlpatterns += [
    path('jobs/prepare/', job_views.PrepareJobs.as_view(), name='prepare_jobs'),
    path('jobs/progress/', job_views.ProgressJobs.as_view(), name='progress_jobs'),
    path('jobs/student/', job_views.StudentJobs.as_view(), name='student_jobs'),
    path('jobs/instructor/', job_views.InstructorJobs.as_view(), name='instructor_jobs'),
    path('instructors/search/', job_views.search_instructors, name='search_instructors'),
    path('instructors/<str:username>/jobs/', job_views.InstructorJobsDetails.as_view(), name='instructor_jobs_details'),
    path('students/<str:username>/jobs/', job_views.StudentJobsDetails.as_view(), name='student_jobs_details'),
    path('sessions/<str:session_slug>/jobs/<str:job_slug>/edit/', job_views.edit_job, name='edit_job'),
    path('sessions/<str:session_slug>/jobs/<str:job_slug>/applications/', job_views.show_job_applications, name='show_job_applications'),
    path('sessions/<str:session_slug>/jobs/<str:job_slug>/applicants/summary/', job_views.SummaryApplicants.as_view(), name='summary_applicants'),
    path('sessions/<str:session_slug>/jobs/<str:job_slug>/details/', job_views.show_job, name='show_job'),
    path('sessions/<str:session_slug>/jobs/<str:job_slug>/instructors/add/', job_views.add_job_instructors, name='add_job_instructors'),
    path('sessions/<str:session_slug>/jobs/<str:job_slug>/instructors/delete/', job_views.delete_job_instructors, name='delete_job_instructors'),
    path('job/worktag_setting/delete/', job_views.delete_job_worktag_setting, name='delete_job_worktag_setting'),
    path('app/worktag_setting/delete/', job_views.delete_app_worktag_setting, name='delete_app_worktag_setting'),

    path('func/jobs/report/download/pdf/', job_views.download_job_report_md, name='download_job_report_md'),
    path('func/jobs/report/download/excel/', job_views.download_job_report_excel, name='download_job_report_excel')
]


# Application

urlpatterns += [
    path('applications/send_email/confirmation/', app_views.applications_send_email_confirmation, name='applications_send_email_confirmation'),
    path('applications/send_email/', app_views.applications_send_email, name='applications_send_email'),

    path('sessions/<str:session_slug>/jobs/<str:job_slug>/offer/', app_views.offer_job, name='offer_job'),
    path('applications/email_history/', app_views.email_history, name='email_history'),
    path('emails/<str:email_id>/reminder/', app_views.send_reminder, name='send_reminder'),
    path('applications/decline_reassign/confirmation/', app_views.decline_reassign_confirmation, name='decline_reassign_confirmation'),
    path('applications/decline_reassign/', app_views.decline_reassign, name='decline_reassign'),
    path('applications/<str:app_slug>/terminate/', app_views.terminate, name='terminate'),

    path('applications/dashboard/', app_views.ApplicationsDashboard.as_view(), name='applications_dashboard'),
    path('applications/all/', app_views.AllApplications.as_view(), name='all_applications'),
    path('applications/selected/', app_views.SelectedApplications.as_view(), name='selected_applications'),
    path('applications/offered/', app_views.OfferedApplications.as_view(), name='offered_applications'),
    path('applications/accepted/report/admin/', app_views.AcceptedAppsReportAdmin.as_view(), name='accepted_apps_report_admin'),
    path('applications/accepted/workday/', app_views.AcceptedAppsReportWorkday.as_view(), name='accepted_apps_report_workday'),
    path('applications/accepted/', app_views.AcceptedApplications.as_view(), name='accepted_applications'),
    path('applications/declined/', app_views.DeclinedApplications.as_view(), name='declined_applications'),
    path('applications/terminated/', app_views.TerminatedApplications.as_view(), name='terminated_applications'),
    path('applications/accepted/report/observer/', app_views.AcceptedAppsReportObserver.as_view(), name='accepted_apps_report_observer'),
    path('applications/admin_docs/update/', app_views.update_admin_docs, name='update_admin_docs'),
    path('applications/accepted/download/workday/', app_views.download_accepted_apps_workday, name='download_accepted_apps_workday'),
    path('applications/accepted/import/', app_views.import_accepted_apps, name='import_accepted_apps'),
    path('applications/reset/', app_views.reset_application, name='reset_application'),

    path('applications/<str:app_slug>/details/', app_views.ShowApplication.as_view(), name='show_application'),

    path('func/applications/accepted/download/all/', app_views.download_all_accepted_apps, name='download_all_accepted_apps'),
    path('func/applications/accepted/report/admin/download/all/', app_views.download_all_accepted_apps_report_admin, name='download_all_accepted_apps_report_admin'),
    path('func/applications/applied/preferred_candidate/download/', app_views.download_preferred_candidates, name='download_preferred_candidates')
]


# Course

urlpatterns += [
    path('courses/all/', course_views.all_courses, name='all_courses'),
    path('courses/create/', course_views.create_course, name='create_course'),
    path('courses/delete/', course_views.delete_course, name='delete_course'),
    path('courses/<str:course_slug>/edit/', course_views.edit_course, name='edit_course')
]


# HR

urlpatterns += [
    path('hr/users/<str:username>/edit/', hr_views.edit_user, name='edit_user'),
    path('hr/users/<str:username>/delete/confirmation/', hr_views.delete_user_confirmation, name='delete_user_confirmation'),
    path('hr/users/all/', hr_views.all_users, name='all_users'),
    path('hr/users/destroy/contents/', hr_views.destroy_user_contents, name='destroy_user_contents'),
    path('hr/users/create/', hr_views.create_user, name='create_user'),

    path('hr/roles/<str:slug>/edit/', hr_views.edit_role, name='edit_role'),
    path('hr/roles/delete/', hr_views.delete_role, name='delete_role'),
    path('hr/roles/', hr_views.roles, name='roles')
]


# Preparation

urlpatterns += [
    path('preparation/terms/delete/', prep_views.delete_term, name='delete_term'),
    path('preparation/terms/<int:term_id>/edit/', prep_views.edit_term, name='edit_term'),
    path('preparation/terms/', prep_views.terms, name='terms'),

    path('preparation/course_codes/delete/', prep_views.delete_course_code, name='delete_course_code'),
    path('preparation/course_codes/<int:course_code_id>/edit/', prep_views.edit_course_code, name='edit_course_code'),
    path('preparation/course_codes/', prep_views.course_codes, name='course_codes'),

    path('preparation/course_numbers/delete/', prep_views.delete_course_number, name='delete_course_number'),
    path('preparation/course_numbers/<int:course_number_id>/edit/', prep_views.edit_course_number, name='edit_course_number'),
    path('preparation/course_numbers/', prep_views.course_numbers, name='course_numbers'),

    path('preparation/course_sections/delete/', prep_views.delete_course_section, name='delete_course_section'),
    path('preparation/course_sections/<int:course_section_id>/edit/', prep_views.edit_course_section, name='edit_course_section'),
    path('preparation/course_sections/', prep_views.course_sections, name='course_sections'),

    path('preparation/statuses/delete/', prep_views.delete_status, name='delete_status'),
    path('preparation/statuses/<str:slug>/edit/', prep_views.edit_status, name='edit_status'),
    path('preparation/statuses/', prep_views.statuses, name='statuses'),

    path('preparation/faculties/delete/', prep_views.delete_faculty, name='delete_faculty'),
    path('preparation/faculties/<str:slug>/edit/', prep_views.edit_faculty, name='edit_faculty'),
    path('preparation/faculties/', prep_views.faculties, name='faculties'),

    path('preparation/programs/delete/', prep_views.delete_program, name='delete_program'),
    path('preparation/programs/<str:slug>/edit/', prep_views.edit_program, name='edit_program'),
    path('preparation/programs/', prep_views.programs, name='programs'),

    path('preparation/degrees/delete/', prep_views.delete_degree, name='delete_degree'),
    path('preparation/degrees/<str:slug>/edit/', prep_views.edit_degree, name='edit_degree'),
    path('preparation/degrees/', prep_views.degrees, name='degrees'),

    path('preparation/trainings/delete/', prep_views.delete_training, name='delete_training'),

instructors/urls.py
from django.urls import path
from . import views

app_name = 'instructors'

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('users/edit/', views.EditUser.as_view(), name='edit_user'),
    path('jobs/', views.ShowJobs.as_view(), name='show_jobs'),
    path('sessions/<str:session_slug>/jobs/<str:job_slug>/edit/', views.EditJob.as_view(), name='edit_job'),
    path('sessions/<str:session_slug>/jobs/<str:job_slug>/applications/', views.ShowApplications.as_view(), name='show_applications'),
    path('sessions/<str:session_slug>/jobs/<str:job_slug>/details/', views.ShowJob.as_view(), name='show_job'),
    path('sessions/<str:session_slug>/jobs/<str:job_slug>/applicants/summary-applicants/', views.SummaryApplicants.as_view(), name='summary_applicants'),
    path('applications/<str:app_slug>/write-note/', views.write_note, name='write_note'),
    path('applicants/send_email/confirmation', views.applicants_send_email_confirmation, name='applicants_send_email_confirmation'),
    path('applicants/send_email/', views.applicants_send_email, name='applicants_send_email'),
    path('emails/history/', views.show_email_history, name='show_email_history')
]

students/urls.py
from django.urls import path
from . import views

app_name = 'students'

urlpatterns = [
    path('', views.Index.as_view(), name='index'),

    path('profile/edit/', views.EditProfile.as_view(), name='edit_profile'),
    path('profile/reminder/confirm/', views.confirm_profile_reminder, name='confirm_profile_reminder'),
    path('profile/information/ta/update/', views.update_profile_ta, name='update_profile_ta'),
    path('profile/information/', views.ShowProfile.as_view(), name='show_profile'),
    path('profile/resume/upload/', views.upload_resume, name='upload_resume'),
    path('profile/resume/delete/', views.delete_resume, name='delete_resume'),

    path('confidential_information/check/', views.check_confidentiality, name='check_confidentiality'),
    path('confidential_information/submit/', views.submit_confidentiality, name='submit_confidentiality'),
    path('confidential_information/edit/', views.EditConfidentiality.as_view(), name='edit_confidentiality'),
    path('confidential_information/delete/', views.delete_confidential_information, name='delete_confidential_information'),
    path('confidential_information/', views.show_confidentiality, name='show_confidentiality'),

    path('jobs/explore/', views.ExploreJobs.as_view(), name='explore_jobs'),
    path('jobs/history/', views.history_jobs, name='history_jobs'),
    path('jobs/favourite/', views.favourite_jobs, name='favourite_jobs'),
    path('sessions/<str:session_slug>/jobs/<str:job_slug>/apply/', views.ApplyJob.as_view(), name='apply_job'),
    path('sessions/<str:session_slug>/jobs/<str:job_slug>/select-favourite-job/', views.select_favourite_job, name='select_favourite_job'),
    path('sessions/<str:session_slug>/jobs/<str:job_slug>/offered/', views.accept_decline_job, name='accept_decline_job'),
    path('sessions/<str:session_slug>/jobs/<str:job_slug>/make_decision/', views.make_decision, name='make_decision'),
    path('sessions/<str:session_slug>/jobs/<str:job_slug>/contract-termination/', views.terminate_job, name='terminate_job'),
    path('sessions/<str:session_slug>/jobs/available/', views.AvailableJobs.as_view(), name='available_jobs'),
    path('sessions/<str:session_slug>/jobs/<str:job_slug>/details/', views.show_job, name='show_job'),

    path('applications/<str:app_slug>/re-accept/', views.reaccept_application, name='reaccept_application'),
    path('applications/<str:app_slug>/', views.show_application, name='show_application'),

    path('download/users/<str:username>/i/<str:item>/files/<str:filename>/', views.download_file, name='download_file')
]

ta_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import handler400, handler403, handler404, handler500
from ta_app import views

urlpatterns = [
    path('app/users/', include('users.urls')),
    path('app/administrators/', include('administrators.urls')),
    path('app/instructors/', include('instructors.urls')),
    path('app/students/', include('students.urls')),
    path('app/observers/', include('observers.urls')),
    path('app/summernote/', include('django_summernote.urls')),
    path('app/impersonate/', include('impersonate.urls')),

    path('app/', views.app_home, name='app_home'),
    path('logout/', views.site_logout, name='logout'),
    path('', views.landing_page, name='landing_page')
]

if settings.DEBUG:
    urlpatterns += [
        path('admin/', admin.site.urls)
    ]

if settings.LOCAL_LOGIN:
    urlpatterns += [
        path('accounts/', include('accounts.urls'))
    ]

handler400 = views.bad_request
handler403 = views.permission_denied
handler404 = views.page_not_found
handler500 = views.internal_server_error

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('profile/photo/upload/', views.upload_avatar, name='upload_avatar'),
    path('profile/photo/delete/', views.delete_avatar, name='delete_avatar'),
    path('profile/<str:username>/details/', views.show_user, name='show_user'),
]

administrators/views.py
from django.shortcuts import render
from django.views.decorators.cache import never_cache
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import View
from django.utils.decorators import method_decorator
from django.views.decorators.http import require_GET

from ta_app import utils
from administrators import api as adminApi
from users import api as userApi


@method_decorator([never_cache], name='dispatch')
class Index(LoginRequiredMixin, View):
    ''' Index page of Administrator's portal '''

    @method_decorator(require_GET)
    def get(self, request, *args, **kwargs):
        request = userApi.has_admin_access(request, utils.HR)

        apps = adminApi.get_applications()

        today_accepted_apps, today = adminApi.get_accepted_apps_by_day(apps, 'today')
        yesterday_accepted_apps, yesterday = adminApi.get_accepted_apps_by_day(apps, 'yesterday')
        week_ago_accepted_apps, week_ago = adminApi.get_accepted_apps_by_day(apps, 'week_ago')

        context = {
            'loggedin_user': userApi.add_avatar(request.user),
            'accepted_apps': apps.filter(applicationstatus__assigned=utils.ACCEPTED).exclude(applicationstatus__assigned=utils.CANCELLED).order_by('-id').distinct(),
            'today_accepted_apps': today_accepted_apps,
            'today_processed_stats': adminApi.get_processed_stats(today_accepted_apps),
            'yesterday_accepted_apps': yesterday_accepted_apps,
            'yesterday_processed_stats': adminApi.get_processed_stats(yesterday_accepted_apps),
            'week_ago_accepted_apps': week_ago_accepted_apps,
            'week_ago_processed_stats': adminApi.get_processed_stats(week_ago_accepted_apps),
            'today': today,
            'yesterday': yesterday,
            'week_ago': week_ago
        }
        if utils.ADMIN in request.user.roles or utils.SUPERADMIN in request.user.roles:
            sessions = adminApi.get_sessions()
            context['current_sessions'] = sessions.filter(is_archived=False)
            context['archived_sessions'] = sessions.filter(is_archived=True)
            context['apps'] = adminApi.get_applications()
            context['instructors'] = userApi.get_users_by_role(utils.INSTRUCTOR)
            context['students'] = userApi.get_users_by_role(utils.STUDENT)
            context['users'] = userApi.get_users()

        return render(request, 'administrators/index.html', context)

administrators/templates/administrators/hr/all_users.html
{% extends 'ta_app/base.html' %}
{% block content %}

{% include 'administrators/_menu.html' %}
<div>
  {% include 'ta_app/pages/_header.html' with title='All Users' %}

  <div class="row">
    <div class="col-md-6">
      {% include 'ta_app/users/_search_fields.html' with data=users total=total_users path='all_users' %}
    </div>

    <div class="col-md-6">
      <div class="bg-light-gray p-4" style="height:142.8px">
        <h5>Note:</h5>
        <ul class="font-size-sm">
          <li>
            This icon <span class="badge badge-success"><i class="fa fa-check-square-o" aria-hidden="true"></i></span> represents that <code>I am a new employee</code> field is checked.
          </li>
        </ul>
      </div>
    </div>
  </div>

  <table
    class="table table-bordered table-hover table-striped table-responsive-md text-center"
    data-toggle="table"
    data-sortable="true"
    data-classes=""
    data-show-export="true"
    data-show-columns="true"
    data-export-types="['csv']"
  >
    <thead>
      <tr>
        <th data-sortable="true">User<br /> ID</th>
        <th data-sortable="true">First<br /> Name</th>
        <th data-sortable="true">Last<br /> Name</th>
        <th data-sortable="true">Prefered<br /> Name</th>
        <th data-sortable="true">CWL</th>
        <th data-sortable="true">Student<br /> Number</th>
        <th data-sortable="true">Employee<br /> Number</th>
        <th data-sortable="true">E-mail</th>
        <th data-sortable="true">Role</th>
        <th data-sortable="true">Superuser <br />Status</th>
        <th data-sortable="true">Last Login</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      {% for user in users %}
        <tr>
          <td>
            <a class="btn btn-xs btn-info" href="{% url 'users:show_user' username=user.username %}?next={{ new_next }}&p=All Users&t=basic">{{ user.id }}</a>
          </td>
          <td>{{ user.first_name }}</td>
          <td>{{ user.last_name }}</td>
          <td>
            {% if user.profile.preferred_name %}
              {{ user.profile.preferred_name }}
            {% endif %}
          </td>
          <td>{{ user.username }}</td>
          <td>
            {% if user.profile.student_number %}
              {{ user.profile.student_number }}
            {% endif %}
          </td>
          <td>
            {% if user.confidentiality.employee_number %}
              {{ user.confidentiality.employee_number }}
            {% else %}
              <span class="badge badge-danger">NEW</span>
            {% endif %}

            {% if user.confidentiality.is_new_employee == True %}
              <br />
              <span class="badge badge-success"><i class="fa fa-check-square-o" aria-hidden="true"></i></span>
            {% endif %}
          </td>
          <td>{{ user.email }}</td>
          <td>
            {% for role in user.profile.roles.all %}
              {% include 'ta_app/users/_role.html' with data=role.name %}
            {% empty %}
              None
            {% endfor %}
          </td>
          <td>
            {% if user.is_superuser %}
              <i class="fa fa-check-circle text-chocolate font-size-1 vertical-middle" aria-hidden="true"></i>
            {% endif %}
          </td>
          <td>
            {% if user.last_login %}
              <span class="d-none">{{ user.last_login|date:"Y m d z" }}</span>
              {{ user.last_login|date:"N j, Y" }}<br />
              {{ user.last_login|date:"g:i a" }}
            {% else %}
              None
            {% endif %}
          </td>
          <td>
            <div class="btn-toolbar">
              <a class="btn btn-xs btn-link mr-2" href="{% url 'administrators:edit_user' username=user.username %}?next={{ new_next }}&p=All Users">Edit</a>
              <a class="btn btn-xs btn-danger mr-2" href="{% url 'administrators:delete_user_confirmation' username=user.username %}?next={{ new_next }}&p=All Users">Delete</a>
            </div>
            <div class="mt-2">
              {% if loggedin_user.is_superuser %}

                {% for role in user.profile.roles.all %}
                  {% if role.name == "Student" %}
                    <a class="btn btn-xs btn-info" href="/app/impersonate/{{ user.id }}/?next={% url 'students:index' %}">Masquerade</a>
                  {% endif %}

                  {% if role.name == "Instructor" %}
                    <a class="btn btn-xs btn-info" href="/app/impersonate/{{ user.id }}/?next={% url 'instructors:index' %}">Masquerade</a>
                  {% endif %}
                {% endfor %}

              {% endif %}
            </div>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>

  {% include 'ta_app/pages/_table_paginator.html' with data=users %}

</div>

{% endblock %}

administrators/templates/administrators/hr/create_user.html
{% extends 'ta_app/base.html' %}
{% block content %}

{% include 'administrators/_menu.html' %}
<div class="row">
  <div class="col-md-4">
		{% include 'ta_app/pages/_header.html' with title='Create User' %}

    <div class="bg-prompt">
      <div class="prompt p-4 mb-4">
				<h4>Current Users</h4>
				<p>There are <span class="font-weight-bold">{{ users|length }}</span> users.</p>
				<a class="btn btn-outline-primary" href="{% url 'administrators:all_users' %}">Back to All Users</a>
      </div>
    </div>
  </div>

  <div class="col-md-8">
		<div class="board col-11 mx-auto">
			<h3>New User Form</h3>

      <div class="bg-white border p-3">
        <ul class="text-dark mb-0">
          <li>All required fields must be filled. (<small class="text-danger"><i class="fa fa-asterisk" aria-hidden="true"></i></small>: This field is required)</li>
        </ul>
      </div>

			<form action="" method="post">
				{% csrf_token %}

				{% for field in user_form.visible_fields  %}
          <div class="field-wrapper">
            <label for="{{ field.id_for_label }}">
              {{ field.label }}:
              {% if field.name == 'first_name' or field.name == 'last_name' or field.name == 'email' or field.name == 'username' %}
                <small class="text-danger"><i class="fa fa-asterisk" aria-hidden="true"></i></small>
              {% endif %}
            </label>
            {% if field.help_text %}
              <div class="help">{{ field.help_text|safe }}</div>
            {% endif %}
            {{ field }}
          </div>
				{% endfor %}

        {% for field in employee_number_form.visible_fields  %}
					<div class="field-wrapper">
						{{ field.label_tag }}
						{% if field.help_text %}
							<div class="help">{{ field.help_text|safe }}</div>
						{% endif %}
						{{ field }}
					</div>
				{% endfor %}

        {% for field in user_profile_form.visible_fields  %}
          <div class="field-wrapper">
            <label for="{{ field.id_for_label }}">
              {{ field.label }}:
              {% if field.name == 'roles' %}
                <small class="text-danger"><i class="fa fa-asterisk" aria-hidden="true"></i></small>
              {% endif %}
            </label>
            {% if field.help_text %}
              <div class="help">{{ field.help_text|safe }}</div>
            {% endif %}
            {{ field }}
          </div>
				{% endfor %}

        <a class="btn btn-outline-secondary" href="{% url 'administrators:all_users' %}">Cancel</a>
				<input class="btn btn-primary" type="submit" value="Create" />
			</form>

		</div>
  </div>
</div>

{% endblock %}

administrators/templates/administrators/hr/roles.html
{% extends 'ta_app/base.html' %}
{% block content %}
{% include 'administrators/_menu.html' %}

<div class="row">
  <div class="col-md-5">
    {% include 'ta_app/pages/_header.html' with title='Roles' text=roles|length %}

    <div class="bg-prompt">
      <div class="prompt p-4 mb-4">
        <h4>Create Role</h4>

        <form action="" method="post">
          {% csrf_token %}

          {% for field in form.visible_fields  %}
            <div class="field-wrapper">
              {{ field.label_tag }}
              {% if field.help_text %}
                <div class="help">{{ field.help_text|safe }}</div>
              {% endif %}
              {{ field }}
            </div>
          {% endfor %}

          {% for field in form.hidden_fields %}
            {{ field }}
          {% endfor %}

          <input class="btn btn-primary mt-3" type="submit" value="Create" />
        </form>

      </div>
    </div>

  </div>
  <div class="col-md-7">

    <table class="table table-bordered table-hover table-striped table-responsive-md text-center font-size-1">
      <thead>
        <tr>
          <th>ID</th>
          <th>Name</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        {% for role in roles %}
          <tr>
            <td>{{ role.id }}</td>
            <td>{{ role.name }}</td>
            <td>
              <div class="btn-toolbar">
                <button class="btn btn-xs btn-primary mr-2" type="button" data-toggle="modal" data-target="#role-edit-modal-{{ role.id }}">Edit</button>

                <div class="modal fade" id="role-edit-modal-{{ role.id }}" tabindex="-1" role="dialog" aria-labelledby="role-edit-modal-label-{{ role.id }}" aria-hidden="true">
                  <div class="modal-dialog modal-lg" role="document">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h5 class="modal-title text-info" id="role-edit-modal-label-{{ role.id }}">Edit Role</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                      </div>
                      <div class="modal-body text-left">
                        <div class="modal-item">
                          <form action="{% url 'administrators:edit_role' role.slug %}" method="post">
                            {% csrf_token %}
                            <div class="field-wrapper">
                              <label for="id_name_{{ role.id }}">Name:</label>
                              <input id="id_name_{{ role.id }}" type="text" name="name" maxlength="256" value="{{ role.name }}" class="form-control" />
                            </div>
                            <input class="btn btn-primary mt-3" type="submit" value="Update" />
                          </form>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>

                <form action="{% url 'administrators:delete_role' %}" method="post" onsubmit="return confirm('Are you sure to delete {{ role.name }}?');">
                  {% csrf_token %}
                  <input type="hidden" name="role" value="{{ role.id }}" />
                  <input class="btn btn-xs btn-danger" type="submit" value="Delete" />
                </form>
              </div>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>

  </div>
</div>


{% endblock %}

administrators/templates/administrators/hr/view_confidentiality.html
{% extends 'ta_app/base.html' %}
{% block content %}

{% include 'administrators/_menu.html' %}
<div class="row">
  <div class="col-md-4">
    {% include 'ta_app/pages/_left_aside.html' with view_name='users' title='View Confidentiality' data=user %}

    <div class="left-aside-btn-groups">
      <a class="btn btn-outline-primary" href="{% url 'administrators:admin_docs' %}">Back to Admin Documents</a>
    </div>
  </div>

  <div class="col-md-8">
    <div class="board col-11 mx-auto">
      <h3>Details</h3>
      {% include 'ta_app/users/_confidentiality.html' with data=user role='administrator' %}
    </div>
  </div>
</div>

{% endblock %}